remote_theme: "mmistakes/minimal-mistakes"
title: diskover
description: Elasticsearch file system crawler and storage analytics.
show_downloads: true
google_analytics: UA-98866026-1
plugins:
  - jekyll-remote-theme
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
