theme: jekyll-theme-tactile
title: diskover
description: Elasticsearch and Kibana powered filesystem crawler and disk usage analyzer to help find unstructured dark data.
show_downloads: true
google_analytics: UA-98866026-1
