theme: jekyll-theme-minimal
title: Diskover - File System Crawler
description: Diskover is a filesystem crawler that uses Elasticsearch and Kibana to help find unstructured dark data
show_downloads: true
google_analytics: UA-98866026-1
